#!/bin/bash

########
# vars #
########

CLILIST=""
RLIST=""
RGLOBAL=""
INSTALLED=""
RFILENAME=""
GITHUBFILENAME=""
ENVFILENAME=""

########
# fncs #
########

display_help() {
    echo
    echo "{install,install_github,install_local,remove,test,update} R packages."
    echo "  By default performs action for the user and not globally."
    echo
    echo "Usage: ${0} [option...] [R packages]"
    echo
    echo "  -h, --help          display help"
    echo "  -g, --global        perform action globally"
    echo "  -i, --install       install R package(s)"
    echo "  --install_github    install R package(s) from github.com"
    echo "  --install_local     install R package(s) from filesystem"
    echo "  -t, --test          test R package(s)"
    echo "  -r, --remove        remove R package(s)"
    echo "  -u, --update        update R package(s); if no package given update all packages"
    echo
    echo "Example: "
    echo "  ${0} --install dplyr,ggplot2            # install dplyr,ggplot2 packages for the user"
    echo "  ${0} --install_github hadley/rvest      # install hadley/rvest package from github for the user"
    echo "  ${0} --install_local dir/pkg.tgz        # install pkg.tgz package within dir/ on the local filesystem"
    echo "  ${0} --remove dplyr,ggplot2             # remove dplyr,ggplot2 packages for the user"
    echo "  ${0} --test dplyr,ggplot2 -g            # test dplyr,ggplot2 packages globally"
    echo "  ${0} --update                           # update all packages for the user"
    echo
}

create_tmp() {
    echo "$(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
}

check_devtools() {
    # $1 = ENVFILENAME
    # $2 = RGLOBAL
    source /tmp/$1 # read file to get the value of INSTALLED
    rm -f /tmp/$1

    if [ "$INSTALLED" == "1" ]; then
        echo
        echo "devtools is installed"
        echo
    else
        echo
        echo "please install devtools"
        echo
        if [ "$2" == "Y" ]; then
            echo "    $ radon --install devtools -g"
        else
            echo "    $ radon --install devtools"
        fi
        echo
        exit 0
    fi
}

quote_list() {
    # $1 = CLILIST
    local _RLIST=""
    IFS=","
    for i in $1; do
        if [ -z "$_RLIST" ]; then
            _RLIST="'${i}'"
            # RLIST="'${i}'"
        else
            _RLIST+=",'${i}'"
        fi
    done
    echo "$_RLIST"
}

action_global() {
    # $1 = RFILENAME | GITHUBFILENAME
    if [[ "$(uname)" == "Darwin" ]]; then
        sudo R --vanilla < /tmp/$1
    else
        sudo su - -c "R --vanilla < /tmp/$1"
    fi
    rm -f /tmp/$1
}

action_user() {
    # $1 = RFILENAME | GITHUBFILENAME
    R --vanilla < /tmp/$1
    rm -f /tmp/$1
}

install_code() {
    # $1 = RLIST
    # $2 = RFILENAME
    cat <<EOF > /tmp/$2

options('repos'='http://cran.rstudio.com')

install.packages(c($1))

EOF
}

install_github_code() {
    # $1 = RLIST
    # $2 = GITHUBFILENAME
    cat <<EOF > /tmp/$2

library('devtools')
devtools::install_github(c($1))

EOF
}

install_local_code() {
    # $1 = RLIST
    # $2 = RFILENAME
    cat <<EOF > /tmp/$2

install.packages(c($1), repos = NULL, type = 'source')

EOF
}

remove_code() {
    # $1 = RLIST
    # $2 = RFILENAME
    cat <<EOF > /tmp/$2

remove.packages(c($1))

EOF
}

test_code() {
    # $1 = RLIST
    # $2 = RFILENAME
    # $3 = ENVFILENAME
    cat <<EOF > /tmp/$2

options('repos'='http://cran.rstudio.com', 'warn'=-1)

f <- file("/tmp/$3")

check_package <- function(pkg) {
    if (require(pkg, character.only = TRUE)) {
        cat_string <- paste0(pkg, ' library loaded')
        writeLines("export INSTALLED=\"1\"", f)
        close(f)
    } else {
        cat_string <- paste0(pkg, ' library did not load')
        writeLines("export INSTALLED=\"0\"", f)
        close(f)
    }
    cat(cat_string)
}

sink('/dev/null') # suppress output

pkgs <- c($1)

lapply(pkgs, check_package)

sink() # resume producing output
options('warn'=0) # reset warnings

EOF
}

update_code() {
    # $1 = RLIST
    # $2 = RFILENAME
    # $3 = CLILIST
    if [ -z "$3" ]; then
        cat <<EOF > /tmp/$2
        
options('repos'='http://cran.rstudio.com')

update.packages(ask = FALSE)

EOF
    else
        cat <<EOF > /tmp/$2

options('repos'='http://cran.rstudio.com')

update.packages(oldPkgs = c($1), ask = FALSE)

EOF
    fi
}

########
# args #
########

# Use > 1 to consume two arguments per pass in the loop
#   each argument has a corresponding value to go with it
# Use > 0 to consume one or more arguments per pass in the loop
#   some arguments don't have a corresponding value to go with it

while [[ $# > 0 ]]; do
    key="$1"

    case $key in
        -h | --help)
            display_help
            exit 0
            ;;
        -i | --install)
            ACTION="install"
            ;;
        --install_github)
            ACTION="install_github"
            ;;
        --install_local)
            ACTION="install_local"
            ;;
        -r | --remove)
            ACTION="remove"
            ;;
        -t | --test)
            ACTION="test"
            ;;
        -u | --update)
            ACTION="update"
            ;;
        -g | --global)
            RGLOBAL="Y"
            ;;
        *)
            CLILIST="$1" 
            ;;
    esac

    shift

done

##########
# R code #
##########

RFILENAME="$(create_tmp)"
ENVFILENAME="$(create_tmp)"
RLIST="$(quote_list "$CLILIST")"    # return RLIST
                                    # RLIST is a quoted list of packages
                                    #   e.g. dplyr,ggplot2 becomes 'dplyr','ggplot2'


case $ACTION in # side effect is to produce tmp file containing R code
                # install_github creates two tmp files containing R code
    install)
        install_code "$RLIST" "$RFILENAME"
        ;;
    install_github)
        test_code "$(quote_list "devtools")" "$RFILENAME" "$ENVFILENAME"
        GITHUBFILENAME="$(create_tmp)"
        install_github_code "$RLIST" "$GITHUBFILENAME"
        ;;
    install_local)
        install_local_code "$RLIST" "$RFILENAME"
        ;;
    remove)
        remove_code "$RLIST" "$RFILENAME"
        ;;
    test)
        test_code "$RLIST" "$RFILENAME" "$ENVFILENAME" 
        ;;
    update)
        update_code "$RLIST" "$RFILENAME" "$CLILIST"
        ;;
    *)
        echo "Action must be one of install, install_github, remove, test, update" 
        ;;

esac

#######
# run #
#######

echo "${ACTION} the packages ${RLIST}..."
echo

if [ -n "$RGLOBAL" ]; then
    if [ "$ACTION" != "install_github" ]; then
        action_global "$RFILENAME" # execute tmp file with R commands
    else
        action_global "$RFILENAME" # execute tmp file built with test_code
        check_devtools "$ENVFILENAME" "$RGLOBAL" # if devtools not installed, then exit
        action_global "$GITHUBFILENAME" # execute tmp file built with install_github_code
    fi
else
    if [ "$ACTION" != "install_github" ]; then
        action_user "$RFILENAME" # execute tmp file with R commands
    else
        action_user "$RFILENAME" # execute tmp file built with test_code
        check_devtools "$ENVFILENAME" "$RGLOBAL" # if devtools not installed, then exit
        action_user "$GITHUBFILENAME" # execute tmp file built with install_github_code
    fi
fi
